version: "3.8"

services:
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_CONVEX_URL: "${NEXT_PUBLIC_CONVEX_URL}"
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}"
      CLERK_SECRET_KEY: "${CLERK_SECRET_KEY}"
      CLERK_JWT_ISSUER_DOMAIN: "${CLERK_JWT_ISSUER_DOMAIN}"
      FIRECRAWL_API_KEY: "${FIRECRAWL_API_KEY}"
      ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      GROQ_API_KEY: "${GROQ_API_KEY}"
      E2B_API_KEY: "${E2B_API_KEY}"
    command: >
      sh -c "npx convex dev & npm run dev"
    depends_on:
      - convex

  convex:
    image: node:25
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "npm install -g convex && npx convex dev"
